# #######################################################################################
# HYPRLAND CONFIG.
# REORGANIZED FOR BETTER MODULARITY AND SHARABILITY.
# #######################################################################################

# --- CORE ---
source = ~/.config/hypr/configs/theme.conf
source = ~/.config/hypr/configs/settings.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/monitors.conf

# --- RULES & KEYBINDS ---
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/binds.conf

# --- ENVIRONMENT & AUTOSTART ---
source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/execs.conf
source = ~/.config/hypr/configs/devices.conf
