# --- HYPRPAPER CONFIG ---
# Latest v0.45.0+ block syntax

# Preload (still required for now to load images)
# preload = ~/Wallpapers/default.png

# New Wallpaper Block
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/wallpaper/car.jpg
    fit_mode = cover
}

# Fully disable splash text
splash = false

# IPC (set to true to allow live wallpaper changes)
ipc = true
