# --- EXECS (Autostart) ---
# Start Waybar, Dunst, and Wallpaper
exec-once = waybar
exec-once = dunst
exec-once = hyprpaper
exec-once = nm-applet --indicator
exec-once = blueman-applet

# Hypr Ecosystem Tools
exec-once = hypridle
exec-once = hyprpolkitagent

# Idle/Lock (Uncomment if installed)
# exec-once = hyprlock

# Cliphist (Uncomment if installed)
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
